### ISSUE TITLE
Controller/gamepad not working at all (but I found the solution)

### ISSUE THREAD

**Issue by Swipe243** [NomadsReach/Fallout-Anomaly#48]
Please use the below as a template when making your report.

## Describe the bug
The gamepad don't work at all. Not in thé menu. Only keyboard and mouse work.

### Is it already a known issue?
Some people have complain about it on discord 

### Steps to reproduce
Install the wabbajack modlist, connect a gamepad and start the game. In the start menu, the controller don't do anything.

### Environment
 - OS: Windows 10
 -  Dualsense controller.

   

### Contact: 
    
   Please list your discord name if you are in our discord:

Swipe

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

There is a txt file "CustomControlmap.txt" In the modlist where the key code for gamepad are not set. Manually adding these key in the third column resolve the issue.

I used this article to help me set up the keys https://www.nexusmods.com/fallout4/articles/3148

---

**Comment by DILLOY** [comment]
Please use the below as a template when making your report.

## Describe the bug
A clear and concise description of what the bug is.

--- MrDILLOY: upon launching the game I can +press any button+ prompt  with my gamepad,  moving the controls in-game on the gamepad does not work 

### Is it already a known issue?
If so or you are not sure please do not make a new request and see the known issue page.

--- MrDILLOY: it is I saw some people's message about it.

### Steps to reproduce
Steps to reproduce the behavior.

--- MrDILLOY: starting the game and plugging in your gamepad. 

### Environment

MrDILLOY's PC Specs 
--- Windows 11 Home
      32.0 GB Ram 
      Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
      64-bit operating system
      Nvidia Geforce RTX 2060 6gb vram

### Contact: 
    
   Please list your discord name if you are in our discord: 

--- MrDILLOY

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from Discord.

--- Above is the original post, just wanted to give a bit more context.

**Comment by NomadsReach** [comment]
Should now be fixed in the latest dev patch, thanks yall. :)
