### ISSUE TITLE
Crashlog - Condition Boy - Vault Girl

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#52]
## Describe the bug
Changing Condition Boy from Vault Boy to Vault Girl triggered this crash (I think)

### Is it already a known issue?
No

### Steps to reproduce
Open MCM, got to condition boy and swap Vault Boy to Vault Girl

### Contact: 
    
 Please list your discord name if you are in our discord: spookyboi

[crash-2024-03-09-08-12-00.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14545765/crash-2024-03-09-08-12-00.log)

**Comment by NomadsReach** [comment]
[crash-2024-03-09-08-12-00-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14548658/crash-2024-03-09-08-12-00-AUTOSCAN.md)


Seems like your crash was possibly related to Fallsouls, which has reports of crashing and things having issues because of that mod. 

Can you upload your save as well.

**Comment by Spookyboi34** [comment]
Here's the save closest to the crash, I had changed some of the settings in Fall Souls

[Uploading Save5_78CE48C2S416E6E61_Vault111Cryo_000012_20240309081854_1_2.zip…]()

**Comment by NomadsReach** [comment]
As this time vault girl is not supported.
