### ISSUE TITLE
Item drops from animals are prevented by Hunter of the Commonwealth

### ISSUE THREAD

**Issue by BrandonBrowning** [NomadsReach/Fallout-Anomaly#62]
## Describe the bug
any item drops on animals are only dropped if you vaporize them (maybe other ways) because of Hunter of the Commonwealth.  confirmed if i turn on the manual loot option it shows up, but otherwise the options do not grab the loot.  tested on a hand placed legendary near the start of the game

### Is it already a known issue?
No

### Steps to reproduce
- go to the legendary near the start of the game near red rocket
- kill it with bullets
- turn on Hunter of the Commonwealth manual inspect
- see there's a legendary drop
- use all the other hunter options to process the animal
- see you never got the drop
- (optional) repeat and kill it with a laser weapon that causes it to become a pool and loot the weapon (bypasses hunter)

### Environment
- OS: windows

### Contact: 
chickensalad

**Comment by NomadsReach** [comment]
I'm not really sure what your issue is? The way the loot tables are set up that only certain creatures will have a loot table. All others are set by HOTC.

You won't get random items like ammo,stimpak etc as these have been patched out. Regardless, HOTC does not have any major conflicts so if the loot tables off an ash pile are showing then this would be an issue with the mod. I will look more into it.

**Comment by NomadsReach** [comment]
HOTC has been replaced with IHO in this upcoming update.
