### ISSUE TITLE
Balance Suggestions

### ISSUE THREAD

**Issue by NomadsReach** [NomadsReach/Fallout-Anomaly#91]
Hello, everyone! 

Please share what balance changes you would like to see for the upcoming patch.

**Comment by KRANKENHAUS2112** [comment]
more random encounters with raiders n shit

**Comment by Autisticfroging** [comment]
less ammo drop per enemies(some enemies drop 40-250 ammo) more encounter with ghouls.

**Comment by ipodjb5** [comment]
idk if you can do this but a maybe a more lite wight version of maim. Dont get me wrong I like a lot of its features but the healing system itself is very non robust and too in-depth especially for people trying a modpack for the first time maybe a ingame tutorial of sort would help

**Comment by BETIK7O7** [comment]
Replace AN76, wet effects, true storms & pip-pad

**Comment by beryllium22** [comment]
The Damage Effects are a bit too strong imo, Don't get me wrong they shouldnt be removed but i also feel like i shouldn't have to be medic every 10-15 mins. Perhaps allow stim packs to do a tad more in healing limbs but make them rarer? Some of the rifle sights seem to be off from where the bullet actually travels (they shoot a tad upward only seemed to be the m4 like rifles in my playthrough). Turrets are insane atm which makes sense but there are times i feel they are impossible to defeat without cheese. Also some essential meds for injuries are classified as illegal drugs in game and some companions will give a [Dislikes that] event.
idk if its possible but if there could be a way to add increased aim debuffs to npcs when shot would make things feel a tad better ie if i shoot someone in the arm enough i want them to sway around with their aim as if struggling like we do.

**Comment by Vetobandito** [comment]
it's hard for me to suggest balance changes since im new to modding but this definitely captures the feel of stalker anomaly.
It's possible all of my issues would be resolved with an updated tutorial video or guide or something.
I'll just ramble and list off things.

IHO toxic exploding guts seems unnecessary

advanced needs debuffs you too heavily or in a way i don't understand when it is on (yes i look in the perk screen as well as the status screen to see what is going)

sometimes I'm missing max health and don't understand why

I feel like maim + advanced needs is kinda cracked, after turning off advanced needs im starting to have a little bit more fun, and make a bit more progress. maybe a tuned down version of it would be better? i still want to eat and drink but as it is currently you are fighting mods to stay alive and not the game world in some instances.

i picked ghoulish trait right off the bat but i still die by rads? kinda goofy.

Also i think there are too many "things" like finding a container with medical items is nice, but then out of all the medical items it could have, you get potassium instead of a bandage or a painkiller or a suture kit or w/e

same thing with guns and ammo, by the time i get out of sanctuary i have seen probably 20-30 different types of ammo between world loot and the two traders you find early enough and then find guns that don't use any of the ammo on offer. 

currently i am sitting on a pile of tec-9s (odd gun to have be the most common one in the wasteland imo) and 500 .38 ammo all from the raiders. I would really love to keep using the starter pistol because it is bad ass, but no 10mm (i thought there was a fix for this but i guess I'm not sure if i applied it correctly).
